version: '3'
services:

  db-postgres:
    image: "postgres:12.2-alpine"
    container_name: db-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

  backend-app:
    build: ./backend
    container_name: backend
    environment:
      - DB_SERVER=db-postgres
      - POSTGRES_DB=postgres
    ports:
      - 8080:8080
    links:
      - db-postgres

  frontend-ui:
    build: ./frontend
    container_name: frontend
    ports:
      - 9000:80
    links:
      - backend-app


volumes:
  postgres-data: