server:
    port: 8080
spring:
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            dialect: org.hibernate.dialect.PostgresSQL9Dialect
    datasource:
        url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
        username: postgres
        password: admin
        platform: postgres
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 20000
            maximum-pool-size: 5
    flyway:
        url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
        schemas: public
        user: postgres
        password: admin

---

spring:
    profiles: development
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
    flyway:
        url: jdbc:postgresql://localhost:5432/postgres